
package com.hhl.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TestCxfImplService", targetNamespace = "http://hhl.com/", wsdlLocation = "http://localhost:8080/services/testCxf?wsdl")
public class TestCxfImplService
    extends Service
{

    private final static URL TESTCXFIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException TESTCXFIMPLSERVICE_EXCEPTION;
    private final static QName TESTCXFIMPLSERVICE_QNAME = new QName("http://hhl.com/", "TestCxfImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/services/testCxf?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TESTCXFIMPLSERVICE_WSDL_LOCATION = url;
        TESTCXFIMPLSERVICE_EXCEPTION = e;
    }

    public TestCxfImplService() {
        super(__getWsdlLocation(), TESTCXFIMPLSERVICE_QNAME);
    }

    public TestCxfImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TESTCXFIMPLSERVICE_QNAME, features);
    }

    public TestCxfImplService(URL wsdlLocation) {
        super(wsdlLocation, TESTCXFIMPLSERVICE_QNAME);
    }

    public TestCxfImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TESTCXFIMPLSERVICE_QNAME, features);
    }

    public TestCxfImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestCxfImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TestCxf
     */
    @WebEndpoint(name = "TestCxfImplPort")
    public TestCxf getTestCxfImplPort() {
        return super.getPort(new QName("http://hhl.com/", "TestCxfImplPort"), TestCxf.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestCxf
     */
    @WebEndpoint(name = "TestCxfImplPort")
    public TestCxf getTestCxfImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://hhl.com/", "TestCxfImplPort"), TestCxf.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TESTCXFIMPLSERVICE_EXCEPTION!= null) {
            throw TESTCXFIMPLSERVICE_EXCEPTION;
        }
        return TESTCXFIMPLSERVICE_WSDL_LOCATION;
    }

}
