
package com.hhl.webserviceclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TestCxf", targetNamespace = "http://hhl.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TestCxf {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://hhl.com/", className = "com.hhl.webserviceclient.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://hhl.com/", className = "com.hhl.webserviceclient.SayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sss", targetNamespace = "http://hhl.com/", className = "com.hhl.webserviceclient.Sss")
    @ResponseWrapper(localName = "sssResponse", targetNamespace = "http://hhl.com/", className = "com.hhl.webserviceclient.SssResponse")
    public String sss(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

}
